name: dicionario_waiwai
description: "Dicionário das palavras do dicionário Waiwai."

publish_to: "none"

version: 1.0.2+8

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  http: ^1.2.1
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.3
  sqflite_common_ffi: ^2.3.3
  sqflite_common: ^2.5.4
  synchronized: ^3.1.0+1
  flutter_svg: ^2.0.10+1
  internet_connection_checker: ^2.0.0
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.20
  sqlite3: ^2.4.2
  json_annotation: ^4.8.1
  provider: ^6.1.2
  carousel_slider: ^5.0.0
  fluttertoast: ^8.2.8

  drift_dev: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  custom_lint: ^0.6.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/collaborators/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nee
      fonts:
        - asset: assets/fonts/nee.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
